import Head from 'next/head'
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bonsai</title>
        <meta name="description" content="Generated by create next app" />
        <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Button variant="contained">Hello</Button>
      </main>
    </div>
  )
}
